forge 'https://forgeapi.puppet.com/'

# We're not ready for version 9
mod 'puppetlabs/stdlib', :git => 'https://github.com/puppetlabs/puppetlabs-stdlib', :ref => 'v8.6.0'  # '< 9'
mod 'puppetlabs/apt',    :git => 'https://github.com/puppetlabs/puppetlabs-apt',    :ref => 'v9.0.2'  # '< 9.1.0'

mod 'puppetlabs/apache',               :git => 'https://github.com/puppetlabs/puppetlabs-apache',            :ref => 'v8.6.0'  # '~> 8.3'
mod 'puppetlabs/postgresql',           :git => 'https://github.com/puppetlabs/puppetlabs-postgresql',        :ref => 'v9.2.0'  # '>= 7.4.0'
mod 'puppet/redis',                    :git => 'https://github.com/voxpupuli/puppet-redis',                  :ref => 'v8.8.0'  # '~> 8.5'
mod 'theforeman/dhcp',                 :git => 'https://github.com/theforeman/puppet-dhcp',                  :ref => '9.0.0'  # '>= 9.0.0 < 9.1.0'
mod 'theforeman/dns',                  :git => 'https://github.com/theforeman/puppet-dns',                   :ref => '10.0.0' # '>= 10.0.0 < 10.1.0'
mod 'theforeman/git',                  :git => 'https://github.com/theforeman/puppet-git',                   :ref => '7.2.0'  # '>= 7.2.0 < 7.3.0'
mod 'theforeman/puppetserver_foreman', :git => 'https://github.com/theforeman/puppet-puppetserver_foreman',  :ref => '2.3.0'  # '>= 2.3.0 < 2.4.0'
mod 'theforeman/tftp',                 :git => 'https://github.com/theforeman/puppet-tftp',                  :ref => '8.0.0'  # '>= 8.0.0 < 8.1.0'
mod 'katello/candlepin',               :git => 'https://github.com/theforeman/puppet-candlepin',             :ref => '14.0.0' # '>= 14.0.0 < 14.1.0'
mod 'theforeman/pulpcore',             :git => 'https://github.com/theforeman/puppet-pulpcore',              :ref => '8.2.0'  # '>= 8.2.0 < 8.3.0'
mod 'katello/qpid',                    :git => 'https://github.com/theforeman/puppet-qpid',                  :ref => '10.0.0' # '>= 10.0.0 < 10.1.0'
mod 'theforeman/foreman',              :git => 'https://github.com/theforeman/puppet-foreman',               :ref => '23.0.0' # '>= 23.0.0 < 23.1.0'
mod 'theforeman/foreman_proxy',        :git => 'https://github.com/theforeman/puppet-foreman_proxy',         :ref => '25.0.0' # '>= 25.0.0 < 25.1.0'
mod 'theforeman/puppet',               :git => 'https://github.com/theforeman/puppet-puppet',                :ref => '17.1.0' # '>= 17.1.0 < 17.2.0'
mod 'katello/foreman_proxy_content',   :git => 'https://github.com/theforeman/puppet-foreman_proxy_content', :ref => '24.2.0' # '>= 24.2.0 < 24.3.0'
mod 'katello/certs',                   :git => 'https://github.com/theforeman/puppet-certs',                 :ref => '16.0.2' # '>= 16.0.2 < 16.1.0'
mod 'katello/katello',                 :git => 'https://github.com/theforeman/puppet-katello',               :ref => '23.1.0' # '>= 23.1.0 < 23.2.0'

mod 'puppet/extlib',      :git => 'https://github.com/voxpupuli/puppet-extlib',       :ref => 'v6.2.0'
mod 'puppet/mosquitto',   :git => 'https://github.com/voxpupuli/puppet-mosquitto',    :ref => 'v1.2.0'
mod 'puppet/systemd',     :git => 'https://github.com/voxpupuli/puppet-systemd',      :ref => 'v4.2.0'
mod 'puppet/trusted_ca',  :git => 'https://github.com/voxpupuli/puppet-trusted_ca',   :ref => 'v4.1.0'
mod 'puppetlabs/concat',  :git => 'https://github.com/puppetlabs/puppetlabs-concat',  :ref => 'v7.4.0'
mod 'puppetlabs/inifile', :git => 'https://github.com/puppetlabs/puppetlabs-inifile', :ref => 'v5.4.1'
mod 'richardc/datacat',   :git => 'https://github.com/richardc/puppet-datacat',       :ref => '0.6.2'
